### ISSUE TITLE
uboot/buildroot is not builded

### ISSUE THREAD

**Issue by sduponch** [SolidRun/clearfog-gt-8k-build#2]
https://github.com/SolidRun/clearfog-gt-8k-build/blob/b0f77ab5ade3bb637ffa6606260db61256fb5929/buildme.sh#L127

cp: impossible d'évaluer 'build/buildroot/output/images/rootfs.cpio.uboot': Aucun fichier ou dossier de ce type

**Comment by Owersun** [comment]
What for you need the buildroot? Kernel is streamlined right inside ubuntu server image, that's more than enough to have the working system

**Comment by sduponch** [comment]
I was just wondering why the image on my SD-Card wasn't booting and i just look for error messages.

If buildroot is not required you should comment this too :
https://github.com/SolidRun/clearfog-gt-8k-build/blob/master/buildme.sh#L141

Now i understand how the u-boot (flash-image.bin) is build and you can close this issue.
